name: CI - MLflow Tuning + Docker + Artifact

on:
  push:
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI: file://$(pwd)/mlruns

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.7

    - name: Check Env
      run: |
        echo "Python version: $(python --version)"
        echo "Current directory: $(pwd)"

    - name: Install dependencies
      run: |
        pip install -r MLProject/requirements.txt || true
        pip install mlflow==2.19.0

    - name: Run mlflow project
      run: |
        export MLFLOW_TRACKING_URI=file://$(pwd)/mlruns
        mlflow run MLProject/ --env-manager=local

    - name: Get latest MLflow run_id
      id: get_run
      run: |
        RUN_ID=$(ls -td mlruns/0/* | head -1 | xargs basename)
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

    - name: Install Python dependencies (for Docker container)
      run: pip install mlflow

    - name: Upload to GitHub (as artifact)
      uses: actions/upload-artifact@8dcacd84f648cd9c8cc6c4998aa6e0d2f3f4f80d
      with:
        name: mlruns-folder
        path: mlruns/

    - name: Build Docker Model
      run: |
        mlflow models build-docker -m "mlruns/0/$RUN_ID/artifacts/model" -n mlflow-model-image

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag Docker Image
      run: docker tag mlflow-model-image:latest fikrifaizz/mlflow-training:latest

    - name: Push Docker Image
      run: docker push fikrifaizz/mlflow-training:latest