name: CI - MLflow Tuning + Docker + Artifact

on:
  push:
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI: file://${{ github.workspace }}/mlruns

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.7

    - name: Install MLflow and dependencies
      run: |
        pip install mlflow==2.19.0 scikit-learn pandas joblib

    - name: Run MLflow project
      run: |
        export MLFLOW_RUN_USE_CONDA=false
        mlflow run MLProject/

    - name: Get MLflow latest run ID
      id: get_run
      run: |
        RUN_ID=$(ls -td mlruns/0/* | head -1 | xargs basename)
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

    - name: Build Docker image with MLflow
      run: |
        mlflow models build-docker -m "mlruns/0/$RUN_ID/artifacts/model" --name mlflow_training_image

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker tag mlflow_training_image:latest fikrifaizz/mlflow-training:latest
        docker push fikrifaizz/mlflow-training:latest

    - name: Upload artifact to GitHub
      uses: actions/upload-artifact@main
      with:
        name: mlflow-artifacts
        path: mlruns/