name: CI - MLflow Tuning + Docker + Artifact

on:
  push:
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI: file://$(pwd)/mlruns

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: MLProject/conda.yaml
        activate-environment: mlflow-env
        auto-activate-base: false
        python-version: 3.12

    - name: Run MLflow project (with conda.yaml)
      shell: bash -l {0}
      run: |
        cd MLProject
        mlflow run . --env-manager=local

    - name: Get latest run ID
      id: get_run
      run: |
        RUN_ID=$(ls -td mlruns/0/* | head -1 | xargs basename)
        echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

    - name: Upload mlruns as artifact
      uses: actions/upload-artifact@main
      with:
        name: mlruns
        path: mlruns/

    - name: Install mlflow CLI
      run: pip install mlflow

    - name: Build Docker Image from MLflow Model
      run: |
        mlflow models build-docker -m "mlruns/0/${{ steps.get_run.outputs.run_id }}/artifacts/model" -n mlflow-model-image

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag Docker image
      run: docker tag mlflow-model-image:latest fikrifaizz/mlflow-training:latest

    - name: Push Docker image
      run: docker push fikrifaizz/mlflow-training:latest